Array Creation and Manipulation:
1.	Create a 1D array with integers from 1 to 10.
2.	Create a 2D array with shape (3, 4) filled with random values.
3.	Create a 3x3 identity matrix.
4.	Generate a sequence of numbers from 0 to 2 with a step of 0.5.
5.	Create a copy of an existing array and change an element in the copy without affecting the original.


In [266]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [267]:
array_2d=np.random.rand(3,4)
array_2d

array([[0.70818256, 0.69619308, 0.71359329, 0.46844895],
       [0.11870248, 0.02243939, 0.39393779, 0.670498  ],
       [0.62718631, 0.56060623, 0.55425566, 0.69207106]])

In [268]:
identity_matrix=np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [269]:
seq_arr=np.arange(0,2.1,0.5)
seq_arr

array([0. , 0.5, 1. , 1.5, 2. ])

In [270]:
orig_arr=np.array([1,32,56])
copied_arr=orig_arr.copy()
copied_arr[0]=45
copied_arr

array([45, 32, 56])

Array Operations:
1.	Perform element-wise addition on two 1D arrays.
2.	Multiply each element in a 2D array by a scalar value.
3.	Subtract the mean of each column from a 2D array.
4.	Find the sum, minimum, and maximum values in a 1D arr
5.	Find the mean, median and mode values in a 1D array.a6.
5.	Normalize a 1D array by scaling its values between 0 and 1.


In [271]:
arr1=np.array([1,3,5,6,7])
arr2=np.array([1,4,6,8,9]) 
addition=np.add(arr1,arr2)
addition

array([ 2,  7, 11, 14, 16])

In [272]:
arr_2d=np.array([[1,3,8,3],[4,7,4,9]])
scalar_value=2
arr_prod=np.multiply(arr_2d,scalar_value)
arr_prod

array([[ 2,  6, 16,  6],
       [ 8, 14,  8, 18]])

In [273]:
arr_2d=np.array([[1,3,8,3],[4,7,4,9]])
mean_subtracted_array = arr_2d - np.mean(arr_2d, axis=0)
mean_subtracted_array

array([[-1.5, -2. ,  2. , -3. ],
       [ 1.5,  2. , -2. ,  3. ]])

In [274]:
arr=np.array([1,3,4])
np.sum(arr)

8

In [275]:
arr=np.array([1,3,4])
np.max(arr)

4

In [276]:
arr=np.array([1,3,4])
np.min(arr)

1

In [ ]:
arr=np.array([1,3,4])
np.mean(arr)

In [ ]:
arr=np.array([1,3,4])
np.median(arr)

In [ ]:
import statistics as stats
arr=np.array([1,3,4])
stats.mode(arr)

In [ ]:
arr_1d=np.array([1,6,8,9,0])
normalized_array = (arr_1d - np.min(arr_1d)) / (np.max(arr_1d) - np.min(arr_1d))
normalized_array

Indexing and Slicing:
1.	Extract the second and third elements from a 1D array.
3.	Select all even-indexed elements from a 1D array.
4.	Replace values greater than 5 in a 1D array with 0.
5.	Sort the elements in a 1D array.

In [ ]:
arr_1d=np.array([1,6,8,9,0])
arr_1d[1:3]

In [ ]:
arr_1d=np.array([1,6,8,9,0])
fd=arr_1d % 2 == 0
fd

In [ ]:
arr_1d=np.array([1,6,8,9,10,15,2,1,4])
arr_1d[arr_1d>5]=0
print(arr_1d)

In [ ]:
arr_1d=np.array([1,6,8,9,10,15,2,19,4])
np.sort(arr_1d)

Mathematical Functions
1.	Calculate the square root of each element in a 1D array.
2.	Compute the exponential of each element in a 1D array.
3.	Compute the power of each element in a 1D array.
4.	Round the values in a 1D array to the nearest integer.
5.	Calculate the mean of a 2D array.
6.	Calculate the standard deviation of a 2D array and then calculate the variance from the standard deviation.
7.	Calculate the variance of a 2D array.
8.	Perform element-wise multiplication of two 2D arrays.


In [ ]:
arr_1=np.array([ 1,  2,  4,  6,  8,  9])
np.sqrt(arr_1)


In [ ]:
arr_1=np.array([ 1,  2,  4,  6,  8,  9])
np.exp(arr_1)


In [ ]:
arr_1=np.array([ 1,  2,  4,  6,  8,  9])
np.power(arr_1, 2)


In [ ]:
arr_1d=np.array([ 1.76868,  2.43345,  4.35436,  6.657658,  8.345,  9.09])
np.round(arr_1d)

In [ ]:
array_2d=np.array([[ 1,  6,  8,  9, 10],[11, 15,  2, 19,  4]])
np.mean(array_2d) 

In [ ]:
array_2d=np.array([[ 1,  6,  8,  9, 10],[11, 15,  2, 19,  4]])
std=np.std(array_2d) 
std

In [ ]:
std**2

In [ ]:
array_2d=np.array([[ 1,  6,  8,  9, 10],[11, 15,  2, 19,  4]])
var=np.var(array_2d) 
var


In [ ]:
 _2d_arr=np.array([[ 1,  6,  1,  9, 1],[1, 1,  2, 1,  4]])
array_2d=np.array([[ 1,  6,  8,  9, 10],[11, 15,  2, 19,  4]])
np.multiply(array_2d, _2d_arr)

Universal Functions (ufuncs)
1.	Calculate the sine of each element in a 1D array.
2.	Compute the element-wise absolute values of a 1D array.
3.	Find the element-wise logarithm (base 10) of a 1D array.
4.	Round down the values in a 1D array to the nearest integer.
5.	Calculate the cumulative sum of elements in a 1D array.


In [ ]:
arr_1d=np.array([1,6,8,9,0])
np.sin(arr_1d)

In [ ]:
arr_1d=np.array([1,6,8,9,0])
np.abs(arr_1d)

In [ ]:
arr_1d=np.array([1,6,8,9,19])
np.log10(arr_1d)

In [ ]:
arr_1d=np.array([ 1.68,  2.45,  3.36,  6.8,  8.5,  9.0])
np.round(arr_1d)

In [ ]:
arr_1d=np.array([1,6,8,9,19])
np.cumsum(arr_1d)

Array Manipulation
1.	Stack two 1D arrays vertically.
2.	Stack two 1D arrays horizontically.
3.	Concatenate two 2D arrays along the rows (axis=0).
4.	Concatenate two 2D arrays along the columns (axis=1).
5.	Split a 1D array into three equal-sized parts.
6.	Insert a new row of zeros at the bottom of a 2D array.
7.	Delete the second column from a 2D array.


In [ ]:
arr_d1=np.array([3,6,8,9,4])
arr_1d=np.array([6,5,6,3,1])
vstack = np.vstack((arr_d1, arr_1d))
vstack

In [ ]:
arr_1d=np.array([3,6,8,9,4])
arr_d1=np.array([6,5,6,3,1])
np.hstack((arr_1d,arr_d1))

In [ ]:
arr_2d=np.array([[3,6,8,9,4],[6,5,6,3,1]])
arr_d2=np.array([[6,5,6,3,1],[3,6,8,9,4]])
np.concatenate((arr_2d,arr_d2), axis=0)

In [ ]:
arr_2d=np.array([[3,6,8,9,4],[6,5,6,3,1]])
arr_d2=np.array([[6,5,6,3,1],[3,6,8,9,4]])
np.concatenate((arr_2d,arr_d2), axis=1)

In [ ]:
arr_d1=np.array([3,6,8,9,4,7])
np.split(arr_d1,3)

In [ ]:
arr_2d=np.array([[3,6,8,9,4],[6,5,6,3,1]])
arr_zero=np.zeros(5)
np.append(arr_zero,arr_2d)

In [ ]:
arr_2d=np.array([[3,6,8,9,4],[6,5,6,3,1]])
np.delete(arr_2d,1,axis=0)

In [ ]:
# np.delete: This function is used to remove specified elements along a given axis from an     array.
# arr_2d: The original 2D array from which you want to remove elements.
# (1) is the index (or indices) of the element(s) you want to remove. In this case, it's       the second column, so the index is 1.
# axis=1: Specifies that the deletion should occur along axis 1 (columns). If axis is not      specified, it is assumed to be a flattened array.

Statistical Operations
1.	Calculate the correlation coefficient between two 1D arrays.
2.	Find the percentile (e.g., 25th and 75th) values of a 1D array.	
3.	Count the number of occurrences of a specific value in a 1D array.
4.	Identify the indices of the minimum and maximum values in a 1D array.

In [ ]:
profit=np.array([2000,3000,4000,100])
sale=np.array([1000,500,1500,300])
np.corrcoef(profit,sale)

In [ ]:
arr_d1=np.array([3,6,8,9,4,7])
np.percentile(arr_d1,[25,75])

In [ ]:
array=np.array([3,7,6,5,4,6,8,9,4,7])
np.count_nonzero(array == 4)


In [278]:
min_index = np.argmin(array)
max_index = np.argmax(array)
print(f"min_index = {min_index}")
print(f"max_index = {max_index}")


min_index = 0
max_index = 7


Linear Algebra
1.	Compute the dot product of two 1D arrays.
2.	Solve a system of linear equations represented by matrices.
3.	Calculate the determinant of a square matrix.
5.	Perform a matrix inversion on a 3x3 matrix.


In [279]:
ar1=np.array([3,7,6,5,4])
ar2=np.array([6,8,9,4,7])
np.dot(ar1,ar2)

176

In [280]:
A = np.array([[2, 3], [4, 5]])
b = np.array([8, 18])
solution = np.linalg.solve(A, b)
solution 

array([ 7., -2.])

In [281]:
arr_2d=np.array([[3,6],[6,5]])
matrix_det = np.linalg.det(arr_2d)
matrix_det

-21.0

In [282]:
matrix_inverse = np.linalg.inv(np.random.rand(3, 3))
matrix_inverse

array([[ 1.62757503,  0.05166197, -0.39824192],
       [ 0.11913499, -3.2459474 ,  2.32849268],
       [-1.73953209,  1.68660535,  0.25290426]])

In [284]:
arr_2d=np.array([[1,7],[6,5]])
print(arr_2d)
print("Transpose:")
print(arr_2d.T)

[[1 7]
 [6 5]]
Transpose:
[[1 6]
 [7 5]]


In [ ]:
ran_arr=np.random.rand(3,3).T
ran_arr